### ISSUE TITLE
Incorrect travis tests

### ISSUE THREAD

**Issue by dtrussel** [pgmpy/pgmpy#882]
Just had quick look at job log from your latest travis build. Looks like you are not really testing against python 3.4 and 3.5, but correct me if i am wrong.

From the log:
`

Setting environment variables from .travis.yml
$ export DISTRIB="conda"
$ export PYTHON_VERSION="3.4"
$ export COVERAGE="true"
$ source ~/virtualenv/python2.7/bin/activate
$ python --version
Python 2.7.12
$ pip --version
pip 8.1.2 from /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages (python 2.7)

`

**Comment by khalibartan** [comment]
@DaveTrussel Indeed, the python version is being shown 2.7.12 in all the other builds. Thanks for reporting about it. Looks like travis has just made some changes it might be related to that. We will look into it.

Ping @ankurankan .

**Comment by khalibartan** [comment]
@ankurankan Can you explain this ? Is it the correct behavior? I never really gave a good glance on environment variables during set up of travis build. But seeing from this I guess we are indeed not testing it in python 3.4 , 3.5 envs.

**Comment by dtrussel** [comment]
Looks like a wrong virtuelenv is activated before the tests. I only started using travis recently and for C++ but from their documentation I would say that something like this should work for your `.travis.yml`:

```
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - build-essential

before_install:
    - pip install coverage coveralls

    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file requirements-dev.txt
    - source activate test-environment

    - uname -a
    - free -m
    - df -h
    - ulimit -a

install:
  - pip install .
  - pip install -r requirements.txt
  - conda build your-conda-recipe
  - conda install your-package --use-local

script:
  - nosetests --with-coverage --cover-package=pgmpy

after_success:
    coveralls
notifications:
    email: false
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/e2ce04225e5e5d1ab64c
        on_success: always  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
on_start: false     # default: false
```

and exchange your `your-conda-recipe` and `your-package` in the conda part respectively. However I did not have time to test it.
